application: civil-pattern-254
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/snippets@.*civil-pattern-254\.appspotmail\.com 
  script: receive_email.py
  login: admin

- url: .*
  script: main.py
  secure: always

inbound_services:
- mail