application: crb-snippets-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/snippets@.*crb-snippets-test\.appspotmail\.com
  script: receive_email.app
  login: admin

- url: .*
  script: main.application
  secure: always

inbound_services:
- mail
