application: civil-pattern-254
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/snippets@.*civil-pattern-254\.appspotmail\.com
  script: receive_email.app
  login: admin

- url: .*
  script: main.app
  secure: always

inbound_services:
- mail